# Config file for automatic testing at travis-ci.org

language: python

sudo: false

python:
  - 3.4
  - 3.3
  - 2.7
  - 2.6

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox virtualenv
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; export TOX_ENV=py26; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export TOX_ENV=py27; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then export TOX_ENV=py33; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then export TOX_ENV=py34; fi"

# command to run tests, e.g. python setup.py test
script: tox -e$TOX_ENV

after_success: coveralls

matrix:
  allow_failures:
    - python: 3.3
    - python: 3.4
