# Config file for automatic testing at travis-ci.org

language: python

sudo: false

env:
  global:
  - LANG='en_US.UTF-8'
  matrix:
    - TOXENV=pep8
    - TOXENV=isort
    - TOXENV=py35
    - TOXENV=py34
    - TOXENV=py33
    - TOXENV=py27
    - TOXENV=py26

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox virtualenv coveralls
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"

# command to run tests, e.g. python setup.py test
script: COMMAND='coverage run --source=djangocms_installer' tox -e$TOXENV

after_success: coveralls
